library_manage/account/urls.py
from django.urls import path
from . import views

from borrowingmanagement.views import borrow_book
from bookmanagement.urls import book_list

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/',views.logoutform, name='logout'),
    path('login/',views.loginview, name='login'),  
    path('register', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('admin', views.admin, name='admin'),
    path('search/', views.search, name = 'search-books'),    
    path('search_author/', views.search_author, name = 'search-author'),  
    path('status_filter', views.status_filter, name='status_filter'),  
    path('filtered_books/<str:genre>/', views.filtered_books, name='filtered_books'),
    path('profile/', views.profile, name = "profile"), 
    path('borrow/',borrow_book, name = 'borrow' ),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('books/',book_list, name = 'books' )
   
]

library_manage/bookmanagement/urls.py
from django.urls import path
from .views import *

app_name = 'bookmanagement'

urlpatterns = [
    path('booklist', book_list, name='book_list'),
    path('AddBook', add_book, name='add_book'),
    path('editbook/', editbookview, name='editbook'),
    path('editbook/edit', edit_book),
    path('deletebook', delete_book, name='delete_book'),
    path('Borrowed',borrowed, name='borrowed'),
    path('ban',banstudent),
    path('searchBook', book_list_view)
] 

library_manage/library_manage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),              
    path('books/', include('bookmanagement.urls')),  
    path('borrowings/', include('borrowingmanagement.urls')), 
    path('reviews/', include('reviewsmanagement.urls',namespace='reviews')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_manage/bookmanagement/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    # book_file=models.FileField(upload_to='books_pdfs', default= "")
    book_cover=models.ImageField(upload_to='books_image', default = "")
    ratings=models.DecimalField(max_digits=3, decimal_places=1, default = 2)
    status_choices = [
        ('available', 'Available'),
        ('borrowed', 'Borrowed'),
    ]
    status = models.CharField(max_length=20, choices=status_choices, default='available')
     

    def calculate_average_rating(self):
    
        # Calculate the average rating based on related reviews
        reviews = self.review_set.all()
        if reviews:
            total_ratings = sum(review.rating for review in reviews)
            average_rating = total_ratings / len(reviews)
            self.ratings = average_rating
        else:
            self.ratings = None
        self.save()


    def __str__(self):
        return self.title 

library_manage/bookmanagement/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'genre', 'book_cover',  'ratings', 'status']
        # 'book_file', can be added if online pdf reading feature is wanted

library_manage/bookmanagement/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Book
from account.models import User
from borrowingmanagement.models import BorrowedBook
from django.http import Http404
from django.contrib import messages
from .forms import BookForm

def admin_required(view_func):
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and (request.user.is_superuser or request.user.is_admin):
            return view_func(request, *args, **kwargs)
        else:
            return redirect('login')  # Redirect to login page if not admin or super admin
    return wrapper

@login_required(login_url='login')
@admin_required
def book_list(request):
    books = Book.objects.all()
    us=User.objects.all()
    context={'books':books}
    return render(request, 'bookmanagement/book_list.html', context=context)


@login_required(login_url='login')
@admin_required
def add_book(request):
    if request.method == 'POST':
        # Bind form with POST data and FILES data
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()  # Save form data to create a new book object
            messages.success(request, 'Book added successfully.')
            return redirect('bookmanagement:book_list')
        else:
            messages.error(request, 'Form is not valid. Please check your input.')
    else:
        form = BookForm()  # Create a blank form instance if the request method is not POST
    return render(request, 'bookmanagement/AddBook.html', {'form': form})


@login_required
@admin_required
def edit_book(request):
    if request.method == 'POST':
        book_id = request.POST.get('bookid')
        if book_id:
            try:
                book = Book.objects.get(id=book_id)
                book.title = request.POST.get("title")
                book.author = request.POST.get("author")
                book.genre = request.POST.get("genre")
                book.status = request.POST.get("status")
                
                # Handle file inputs separately from request.POST
                if 'file' in request.FILES:
                    book.book_file = request.FILES['file']
                if 'cover' in request.FILES:
                    book.book_cover = request.FILES['cover']
                    
                book.save()
                return redirect('bookmanagement:book_list')
            except Book.DoesNotExist:
                messages.error(request, "Book not found.")
        else:
            messages.error(request, "Invalid request: No book ID provided.")
    else:
        messages.error(request, "Invalid request method.")
    return redirect('bookmanagement:book_list')


    
@login_required(login_url='login')
@admin_required
def editbookview(request):
        book=Book.objects.get(id=request.GET['bookid'])
        print(book)   
        return render(request,'bookmanagement/editbook.html',{'book':book})



@login_required
@admin_required
def delete_book(request):
    book=Book.objects.get(id=request.GET['bookid'])
    book.delete()
    return redirect('bookmanagement:book_list')
   



def book_list_view(request):
    books = Book.objects.all()
    search_query = request.GET.get('q')
    genre_filter = request.GET.get('genre')
    author_filter = request.GET.get('author')
    status_filter = request.GET.get('status')

    if search_query:
        books = books.filter(title__icontains=search_query)

    if genre_filter:
        books = books.filter(genre=genre_filter)

    if author_filter:
        books = books.filter(author=author_filter)

    if status_filter:
        books = books.filter(status=status_filter)

    return render(request, 'book_list.html', {'books': books})


def borrowed(request):
    books=BorrowedBook.objects.all()
    print(books)
    return render(request, 'bookmanagement/borrowedbook.html', {'books':books})


@login_required
def banstudent(request):

    if not request.user.is_superuser:
        messages.error(request, 'u are not authorized to ban student.')
    if request.method == 'GET' and 'userid' in request.GET:
        user_id = request.GET['userid']
        try:
            user = User.objects.get(id=user_id)
            user.is_banned = True
            user.save()
            messages.success(request, 'Student banned successfully.')
        except User.DoesNotExist:
            messages.error(request, 'Invalid user ID.')
    else:
        messages.error(request, 'Invalid request.')
    return redirect('bookmanagement:borrowed')

library_manage/bookmanagement/templates/bookmanagement/AddBook.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<title>Add | Book</title>
    <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }

    nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px 20px;
      box-shadow:1px 2px 5px  rgba(3, 19, 37,0.5);
      background:rgba(3, 0, 0, 0.8);
        }

    nav ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }

    nav ul li {
      display: inline;
      margin-right: 10px;
    }

    main {
      padding: 20px;
    }

    h1 {
      color: #333;
    }

    .book {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
    }

    .book img {
      width: 100px;
      height: 150px;
      margin-right: 10px;
    }
    
    .table {
      margin-top: 20px;
    }
  </style>


  <style>
    .forms {
      margin-left: 20rem;
    }

    .containerr {
      display: inline-flex;
      margin-top: 4rem;
      margin-bottom: 2rem;
    }

    .containerr h2 {
      margin-left: 10rem;
    }
  </style>
</head>

<body>

  <header>
    <nav>
      <ul>
        <li><a href="{% url 'home' %}" style="color:white; text-decoration: none; font-weight: bold; font-size: 18px;">Home</a></li>
        <li><a href="booklist" style="color:white; text-decoration: none; font-weight: bold; font-size: 18px;">Book Management</a></li>
        <li><a href="AddBook" style="color:white; text-decoration: none; font-weight: bold; font-size: 18px;">Add Books</a></li>
        <li><a href="Borrowed" style="color:white; text-decoration: none; font-weight: bold; font-size: 18px;">Borrowed Books</a></li>
      </ul>
      <ul>
        <li><a href="{% url 'logout' %}" style="color:white; text-decoration: none; font-weight: bold; font-size: 18px;">Logout <i class="fa-solid fa-right-from-bracket"></i></a></li>
      </ul>
      
      </header>
     
  <div class="container">

    <h1 class="mt-2"><i class="fa-solid fa-book"></i> Add Book</h1> <br>

<form class="mt-3" action="AddBook" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Enter title here">
    <small id="titleHelp" class="form-text text-muted">We will try to find your favorite book here!</small>
  </div>
  <div class="form-group">
    <label for="author">Author</label>
    <input type="text" class="form-control" id="author" name="author" placeholder="Enter author here">
  </div>

  <div class="form-group">
    <label for="genre">Genre</label>
    <select class="form-control" id="genre" name="genre">
      <option value="Fictional">Fictional</option>
      <option value="Educational">Educational</option>
      <option value="Drama">Drama</option>
      <option value="Non-Fictional">Non-Fictional</option>
      <option value="Romance">Romance</option>
    </select>
  </div>

  <div class="form-group">
    <label for="book_cover">Book Cover</label>
    <input type="file" class="form-control" id="book_cover" name="book_cover" placeholder="Upload book cover" accept="image/*">
  </div>
  <!-- 
  <div class="form-group">
    <label for="book_file">Book PDF</label>
    <input type="file" class="form-control" id="book_file" name="book_file" placeholder="Upload book PDF" accept=".pdf">
  </div> -->

  <div class="form-group">
    <label for="ratings">Ratings</label>
    <input type="number" class="form-control" id="ratings" name="ratings" placeholder="Enter your personal rating here" min="1" max="5">
  </div>

  <div class="form-group">
    <label for="status">Status</label>
    <select class="form-control" id="status" name="status">
      <option value="available">Available</option>
      <option value="borrowed">Borrowed</option>
    </select>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br>


  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://kit.fontawesome.com/4dc0af90fd.js" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/4dc0af90fd.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

</body>

</html>

library_manage/bookmanagement/templates/bookmanagement/book_list.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
  integrity="sha512-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  crossorigin="anonymous" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }


    nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px 20px;
      box-shadow:1px 2px 5px  rgba(3, 19, 37,0.5);
      background:rgba(3, 0, 0, 0.8);
        }

    nav ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }

    nav ul li {
      display: inline;
      margin-right: 10px;
    }

    main {
      padding: 20px;
    }

    h1 {
      color: #333;
      margin-top:100px;
      text-align:center;
      margin-bottom:100px;
    }

    .book {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
    }

    .book img {
      width: 100px;
      height: 150px;
      margin-right: 10px;
    }
    
    .table {
      margin-top: 20px;
    }
    
  </style>

  <title>All | Books</title>

</head>

<body>

  <header>
    <nav>
      <ul>
        <li><a href="{% url 'home' %}" style=" color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Home</a></li>
        <li><a href="booklist" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Book Management</a></li>
        <li><a href="AddBook" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Add Books</a></li>
        <li><a href="Borrowed" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Borrowed Books</a></li>
      </ul>
      <ul>
        <li><a href="{% url 'logout' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Logout <i class="fa-solid fa-right-from-bracket"></i></a></li>
      </ul>  

    </nav>
  </header>

  <div class="container">
    <h1 class="mt-2"><i class="fa-solid fa-book"></i> All Books </h1>
     {% csrf_token %}
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Title</th>
          <th scope="col">Author</th>
          <th scope="col">Genre</th>
          <th scope="col">Status</th>
        <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for i in books %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ i.title }}</td>
          <td>{{ i.author }}</td>
          <td>{{ i.genre }}</td>
          <td>{{ i.status }}</td>
          <td>   
            <a href="editbook?bookid={{i.id}}"><button type="button" class="btn btn-primary">Edit</button></a>
            &nbsp;
            <a href="deletebook?bookid={{i.id}}"><button type="button" class="btn btn-danger">Delete</button></a>      
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
  <script src="https://kit.fontawesome.com/4dc0af90fd.js" crossorigin="anonymous"></script>
<body>

library_manage/bookmanagement/templates/bookmanagement/borrowedbook.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
    }

    nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px 20px;
      box-shadow:1px 2px 5px  rgba(3, 19, 37,0.5);
      background:rgba(3, 0, 0, 0.8);
        }

    nav ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }

    nav ul li {
      display: inline;
      margin-right: 10px;
    }
    nav ul li a:hover{
      color:#000000;
    }

    main {
      padding: 20px;
    }

    h1 {
      color: #333;
    }

    .book {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
    }

    .book img {
      width: 100px;
      height: 150px;
      margin-right: 10px;
    }
    
    .table {
      margin-top: 20px;
    }

    .table-container {
        margin: 0 auto; /* Center the container horizontally */
        max-width: 70rem; /* Set a maximum width for the table */
      }
      .link:hover{
        color:black;
      }
  </style>

  <title>Borrowed | Books</title>

</head>

<body>

  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a class="link" href="{% url 'home' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Home</a></li>
        <li><a class="link" href="booklist" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Book Management</a></li>
        <li><a class="link" href="AddBook" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Add Books</a></li>
        <li><a class="link" href="#" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Borrowed Books</a></li>
      </ul>
      <ul>
        <li><a class="link" href="{% url 'logout' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Logout <i class="fa-solid fa-right-from-bracket"></i></a></li>
      </ul>
      {% else %}
      <ul>
        <li><a href="register" style="text-decoration: none; font-weight: bold; font-size: 18px;">Register</a></li>
        <li><a href="login" style="text-decoration: none; font-weight: bold; font-size: 18px;">Login</a></li>
      </ul>
      {% endif %}
    </nav>
  </header>


  <h1 class="mt-3" style="margin-bottom: 1rem; text-align: center;"><i class="fa-solid fa-book"></i> Borrowed Books</h1>

  <div class="table-container">
    <table class="table table-striped table-dark">
        <table class="table table-striped table-dark">
            <thead>
              <tr>
                <th scope="col">Book ID</th>
                <th scope="col">Book</th>
                <th scope="col">Borrowed Date</th>
                <th scope="col">Borrowed By</th>
                {% if user.is_superuser %}
      <th scope="col">Action</th>
    {% endif %}
  </tr>
</thead>
<tbody>
  {% for i in books %} 
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ i.book }}</td>
      <td>{{ i.borrow_date }}</td>
      <td>{{ i.user }}</td>
      {% if user.is_superuser %}
        <td>
          <a href="ban?userid={{ i.user.id }}"><button type="button"  class="btn btn-warning">Ban Student</button></a>
        </td>
      {% endif %}
    </tr>
  {% endfor %} 
</tbody>

          </table>
    </table>
    <p>
    {% if msg %}
      msg
    {% endif %}
      </p>
  </div>


  <script src="https://kit.fontawesome.com/4dc0af90fd.js" crossorigin="anonymous"></script>

library_manage/bookmanagement/templates/bookmanagement/editbook.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
        .forms {
            margin-left: 20rem;
        }
    </style>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        nav {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
            box-shadow: 1px 2px 5px rgba(3, 19, 37, 0.5);
            background: rgba(3, 0, 0, 0.8);
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin-right: 10px;
        }

        main {
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-top: 50px;
        }

        .book {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .book img {
            width: 100px;
            height: 150px;
            margin-right: 10px;
        }

        .table {
            margin-top: 20px;
        }
    </style>

    <title>Edit Book</title>
</head>
<body>

<header>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Home</a></li>
            <li><a href="{% url 'bookmanagement:book_list' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Book Management</a></li>
            <li><a href="{% url 'bookmanagement:add_book' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Add Books</a></li>
            <li><a href="{% url 'bookmanagement:borrowed' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Borrowed Books</a></li>
        </ul>
        <ul>
            <li><a href="{% url 'logout' %}" style="color:#fff; text-decoration: none; font-weight: bold; font-size: 18px;">Logout <i class="fa-solid fa-right-from-bracket"></i></a></li>
        </ul>
        </nav>
        </header>
        

    
<div class="container" >

    <h1 mt-2><i class="fa-solid fa-book"></i> Edit Book</h1> <br>

    <form class="mt-4" action="edit" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input type="hidden" name="bookid" value="{{ book.id }}">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title here" value="{{ book.title }}">
            <small id="titleHelp" class="form-text text-muted">We will try to find your favorite book here!</small>
        </div>
        <div class="form-group">
            <label for="author">Author</label>
            <input type="text" class="form-control" id="author" name="author" placeholder="Enter author here" value="{{ book.author }}">
        </div>
        <div class="form-group">
            <label for="genre">Genre</label>
            <select class="form-control" id="genre" name="genre">
                <option value="fictional" {% if book.genre == 'fictional' %} selected {% endif %}>Fictional</option>
                <option value="educational" {% if book.genre == 'educational' %} selected {% endif %}>Educational</option>
                <option value="drama" {% if book.genre == 'drama' %} selected {% endif %}>Drama</option>
                <option value="non-fictional" {% if book.genre == 'non-fictional' %} selected {% endif %}>Non-Fictional</option>
                <option value="romance" {% if book.genre == 'romance' %} selected {% endif %}>Romance</option>
            </select>
        </div>
        <div class="form-group">
            <label for="status">Status</label>
            <input type="text" class="form-control" id="status" name="status" placeholder="Enter status here" value="{{ book.status }}">
        </div>
        <!--
        <div class="form-group">
            <label for="file">Book PDF</label>
            <input type="file" class="form-control" id="file" name="file" placeholder="Enter file here" accept=".PDF">
        </div> -->
        <div class="form-group">
            <label for="cover">Book cover</label>
            <input type="file" class="form-control" id="cover" name="cover" placeholder="Enter cover here" accept="image/*">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <br>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://kit.fontawesome.com/4dc0af90fd.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBv